name: 01 Events

#on: [push, pull_request]
on:
#  pull_request:
#    types: [closed]
#    types:
#      - pull_reques
#      - closed
  push:
    branches: [main]
jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"
