name: 01 Events

on:
  push:
#    branches: [main]
#    branches-ignore: [main]
    tags:
      - v2
jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"
