name: 05-context
run-name: ${{ github.actor}} explaining context data - Try Number ${{ github.run_number }}
on:
  workflow_dispatch

jobs:
  print-context-data:
    runs-on: ubuntu-latest
    steps:
      - name: Print Context Data
        run: echo ${{ toJSON(github) }}
